// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: account/v1/account.proto

package accountv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountNumber string                 `protobuf:"bytes,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Agency        string                 `protobuf:"bytes,4,opt,name=agency,proto3" json:"agency,omitempty"`
	AccountType   string                 `protobuf:"bytes,5,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	Balance       string                 `protobuf:"bytes,6,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency      string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_account_v1_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Account) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *Account) GetAgency() string {
	if x != nil {
		return x.Agency
	}
	return ""
}

func (x *Account) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *Account) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *Account) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Account) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Account) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Account) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountType   string                 `protobuf:"bytes,2,opt,name=account_type,json=accountType,proto3" json:"account_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_account_v1_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAccountRequest) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_account_v1_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_account_v1_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_account_v1_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{4}
}

func (x *GetAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type GetAccountByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountByUserIdRequest) Reset() {
	*x = GetAccountByUserIdRequest{}
	mi := &file_account_v1_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByUserIdRequest) ProtoMessage() {}

func (x *GetAccountByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetAccountByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{5}
}

func (x *GetAccountByUserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAccountByUserIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountByUserIdResponse) Reset() {
	*x = GetAccountByUserIdResponse{}
	mi := &file_account_v1_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByUserIdResponse) ProtoMessage() {}

func (x *GetAccountByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByUserIdResponse.ProtoReflect.Descriptor instead.
func (*GetAccountByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{6}
}

func (x *GetAccountByUserIdResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type GetAccountByNumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber string                 `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountByNumberRequest) Reset() {
	*x = GetAccountByNumberRequest{}
	mi := &file_account_v1_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountByNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByNumberRequest) ProtoMessage() {}

func (x *GetAccountByNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByNumberRequest.ProtoReflect.Descriptor instead.
func (*GetAccountByNumberRequest) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{7}
}

func (x *GetAccountByNumberRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

type GetAccountByNumberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountByNumberResponse) Reset() {
	*x = GetAccountByNumberResponse{}
	mi := &file_account_v1_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountByNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByNumberResponse) ProtoMessage() {}

func (x *GetAccountByNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByNumberResponse.ProtoReflect.Descriptor instead.
func (*GetAccountByNumberResponse) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{8}
}

func (x *GetAccountByNumberResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_account_v1_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{9}
}

func (x *GetBalanceRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Balance       string                 `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_account_v1_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{10}
}

func (x *GetBalanceResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetBalanceResponse) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *GetBalanceResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetBalanceResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type DebitAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	TransactionId string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebitAccountRequest) Reset() {
	*x = DebitAccountRequest{}
	mi := &file_account_v1_account_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebitAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebitAccountRequest) ProtoMessage() {}

func (x *DebitAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebitAccountRequest.ProtoReflect.Descriptor instead.
func (*DebitAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{11}
}

func (x *DebitAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *DebitAccountRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *DebitAccountRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type DebitAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewBalance    string                 `protobuf:"bytes,2,opt,name=new_balance,json=newBalance,proto3" json:"new_balance,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebitAccountResponse) Reset() {
	*x = DebitAccountResponse{}
	mi := &file_account_v1_account_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebitAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebitAccountResponse) ProtoMessage() {}

func (x *DebitAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebitAccountResponse.ProtoReflect.Descriptor instead.
func (*DebitAccountResponse) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{12}
}

func (x *DebitAccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DebitAccountResponse) GetNewBalance() string {
	if x != nil {
		return x.NewBalance
	}
	return ""
}

func (x *DebitAccountResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type CreditAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	TransactionId string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditAccountRequest) Reset() {
	*x = CreditAccountRequest{}
	mi := &file_account_v1_account_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditAccountRequest) ProtoMessage() {}

func (x *CreditAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditAccountRequest.ProtoReflect.Descriptor instead.
func (*CreditAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{13}
}

func (x *CreditAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreditAccountRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CreditAccountRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type CreditAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewBalance    string                 `protobuf:"bytes,2,opt,name=new_balance,json=newBalance,proto3" json:"new_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditAccountResponse) Reset() {
	*x = CreditAccountResponse{}
	mi := &file_account_v1_account_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditAccountResponse) ProtoMessage() {}

func (x *CreditAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_v1_account_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditAccountResponse.ProtoReflect.Descriptor instead.
func (*CreditAccountResponse) Descriptor() ([]byte, []int) {
	return file_account_v1_account_proto_rawDescGZIP(), []int{14}
}

func (x *CreditAccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreditAccountResponse) GetNewBalance() string {
	if x != nil {
		return x.NewBalance
	}
	return ""
}

var File_account_v1_account_proto protoreflect.FileDescriptor

const file_account_v1_account_proto_rawDesc = "" +
	"\n" +
	"\x18account/v1/account.proto\x12\n" +
	"account.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd8\x02\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12%\n" +
	"\x0eaccount_number\x18\x03 \x01(\tR\raccountNumber\x12\x16\n" +
	"\x06agency\x18\x04 \x01(\tR\x06agency\x12!\n" +
	"\faccount_type\x18\x05 \x01(\tR\vaccountType\x12\x18\n" +
	"\abalance\x18\x06 \x01(\tR\abalance\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"R\n" +
	"\x14CreateAccountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\faccount_type\x18\x02 \x01(\tR\vaccountType\"F\n" +
	"\x15CreateAccountResponse\x12-\n" +
	"\aaccount\x18\x01 \x01(\v2\x13.account.v1.AccountR\aaccount\"2\n" +
	"\x11GetAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"C\n" +
	"\x12GetAccountResponse\x12-\n" +
	"\aaccount\x18\x01 \x01(\v2\x13.account.v1.AccountR\aaccount\"4\n" +
	"\x19GetAccountByUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"M\n" +
	"\x1aGetAccountByUserIdResponse\x12/\n" +
	"\baccounts\x18\x01 \x03(\v2\x13.account.v1.AccountR\baccounts\"B\n" +
	"\x19GetAccountByNumberRequest\x12%\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\raccountNumber\"K\n" +
	"\x1aGetAccountByNumberResponse\x12-\n" +
	"\aaccount\x18\x01 \x01(\v2\x13.account.v1.AccountR\aaccount\"2\n" +
	"\x11GetBalanceRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"\xa4\x01\n" +
	"\x12GetBalanceResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\tR\abalance\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"s\n" +
	"\x13DebitAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\"v\n" +
	"\x14DebitAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vnew_balance\x18\x02 \x01(\tR\n" +
	"newBalance\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"t\n" +
	"\x14CreditAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\"R\n" +
	"\x15CreditAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vnew_balance\x18\x02 \x01(\tR\n" +
	"newBalance2\xf3\x04\n" +
	"\x0eAccountService\x12T\n" +
	"\rCreateAccount\x12 .account.v1.CreateAccountRequest\x1a!.account.v1.CreateAccountResponse\x12K\n" +
	"\n" +
	"GetAccount\x12\x1d.account.v1.GetAccountRequest\x1a\x1e.account.v1.GetAccountResponse\x12c\n" +
	"\x12GetAccountByUserId\x12%.account.v1.GetAccountByUserIdRequest\x1a&.account.v1.GetAccountByUserIdResponse\x12c\n" +
	"\x12GetAccountByNumber\x12%.account.v1.GetAccountByNumberRequest\x1a&.account.v1.GetAccountByNumberResponse\x12K\n" +
	"\n" +
	"GetBalance\x12\x1d.account.v1.GetBalanceRequest\x1a\x1e.account.v1.GetBalanceResponse\x12Q\n" +
	"\fDebitAccount\x12\x1f.account.v1.DebitAccountRequest\x1a .account.v1.DebitAccountResponse\x12T\n" +
	"\rCreditAccount\x12 .account.v1.CreditAccountRequest\x1a!.account.v1.CreditAccountResponseB8Z6github.com/buemura/minibank/proto/account/v1;accountv1b\x06proto3"

var (
	file_account_v1_account_proto_rawDescOnce sync.Once
	file_account_v1_account_proto_rawDescData []byte
)

func file_account_v1_account_proto_rawDescGZIP() []byte {
	file_account_v1_account_proto_rawDescOnce.Do(func() {
		file_account_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_v1_account_proto_rawDesc), len(file_account_v1_account_proto_rawDesc)))
	})
	return file_account_v1_account_proto_rawDescData
}

var file_account_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_account_v1_account_proto_goTypes = []any{
	(*Account)(nil),                    // 0: account.v1.Account
	(*CreateAccountRequest)(nil),       // 1: account.v1.CreateAccountRequest
	(*CreateAccountResponse)(nil),      // 2: account.v1.CreateAccountResponse
	(*GetAccountRequest)(nil),          // 3: account.v1.GetAccountRequest
	(*GetAccountResponse)(nil),         // 4: account.v1.GetAccountResponse
	(*GetAccountByUserIdRequest)(nil),  // 5: account.v1.GetAccountByUserIdRequest
	(*GetAccountByUserIdResponse)(nil), // 6: account.v1.GetAccountByUserIdResponse
	(*GetAccountByNumberRequest)(nil),  // 7: account.v1.GetAccountByNumberRequest
	(*GetAccountByNumberResponse)(nil), // 8: account.v1.GetAccountByNumberResponse
	(*GetBalanceRequest)(nil),          // 9: account.v1.GetBalanceRequest
	(*GetBalanceResponse)(nil),         // 10: account.v1.GetBalanceResponse
	(*DebitAccountRequest)(nil),        // 11: account.v1.DebitAccountRequest
	(*DebitAccountResponse)(nil),       // 12: account.v1.DebitAccountResponse
	(*CreditAccountRequest)(nil),       // 13: account.v1.CreditAccountRequest
	(*CreditAccountResponse)(nil),      // 14: account.v1.CreditAccountResponse
	(*timestamppb.Timestamp)(nil),      // 15: google.protobuf.Timestamp
}
var file_account_v1_account_proto_depIdxs = []int32{
	15, // 0: account.v1.Account.created_at:type_name -> google.protobuf.Timestamp
	15, // 1: account.v1.Account.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: account.v1.CreateAccountResponse.account:type_name -> account.v1.Account
	0,  // 3: account.v1.GetAccountResponse.account:type_name -> account.v1.Account
	0,  // 4: account.v1.GetAccountByUserIdResponse.accounts:type_name -> account.v1.Account
	0,  // 5: account.v1.GetAccountByNumberResponse.account:type_name -> account.v1.Account
	15, // 6: account.v1.GetBalanceResponse.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 7: account.v1.AccountService.CreateAccount:input_type -> account.v1.CreateAccountRequest
	3,  // 8: account.v1.AccountService.GetAccount:input_type -> account.v1.GetAccountRequest
	5,  // 9: account.v1.AccountService.GetAccountByUserId:input_type -> account.v1.GetAccountByUserIdRequest
	7,  // 10: account.v1.AccountService.GetAccountByNumber:input_type -> account.v1.GetAccountByNumberRequest
	9,  // 11: account.v1.AccountService.GetBalance:input_type -> account.v1.GetBalanceRequest
	11, // 12: account.v1.AccountService.DebitAccount:input_type -> account.v1.DebitAccountRequest
	13, // 13: account.v1.AccountService.CreditAccount:input_type -> account.v1.CreditAccountRequest
	2,  // 14: account.v1.AccountService.CreateAccount:output_type -> account.v1.CreateAccountResponse
	4,  // 15: account.v1.AccountService.GetAccount:output_type -> account.v1.GetAccountResponse
	6,  // 16: account.v1.AccountService.GetAccountByUserId:output_type -> account.v1.GetAccountByUserIdResponse
	8,  // 17: account.v1.AccountService.GetAccountByNumber:output_type -> account.v1.GetAccountByNumberResponse
	10, // 18: account.v1.AccountService.GetBalance:output_type -> account.v1.GetBalanceResponse
	12, // 19: account.v1.AccountService.DebitAccount:output_type -> account.v1.DebitAccountResponse
	14, // 20: account.v1.AccountService.CreditAccount:output_type -> account.v1.CreditAccountResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_account_v1_account_proto_init() }
func file_account_v1_account_proto_init() {
	if File_account_v1_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_v1_account_proto_rawDesc), len(file_account_v1_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_v1_account_proto_goTypes,
		DependencyIndexes: file_account_v1_account_proto_depIdxs,
		MessageInfos:      file_account_v1_account_proto_msgTypes,
	}.Build()
	File_account_v1_account_proto = out.File
	file_account_v1_account_proto_goTypes = nil
	file_account_v1_account_proto_depIdxs = nil
}
